name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # 사용하려는 Node.js 버전

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y python3-pip
          pip3 install awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region your-aws-region

      - name: Install Nest.js dependencies
        run: |
          cd your-application-directory
          npm install

      - name: Build Nest.js application
        run: |
          cd your-application-directory
          npm run build

      - name: Deploy to Elastic Beanstalk
        run: |
          cd your-application-directory
          eb init -p node.js your-application-name
          eb deploy
